In [35]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Data 6 Fall 2025: Functions and `apply`

### Create functions with a definition

```python
def functionname(Arguments_Parameters_Expressions_or_Values):  
    """docstring"""
      return return_expression
```

### **Task:** Create a function called `triple()` that takes an input `x`  and triples it.

In [ ]:
def triple(x):
    """triples the input"""
    tripled_x = x * 3
    return tripled_x

In [ ]:
triple(3)

In [ ]:
num = 4

In [ ]:
triple(num)

In [ ]:
triple(num * 5)

**Note:** Functions can be type-agnostic, but it depends on what the function does.

In this case, the `*` operator works on arrays and strings, too.

In [ ]:
triple(np.arange(4))

In [ ]:
triple('ha')

**STOP**

##### **Discussion Question [2 min]:** Can you decipher the function `f`?

- What type of input does `f` take?
- What type of output does `f` produce?
- What's a good name for the function (and what might go in the docstring)?

```python
def f(s):    
    """docstring"""
      return np.round(s / sum(s) * 100, 2)
```

<br/><br/><br/>

## Practice

### Return values

Functions are not required to "`return`" anything. If a function doesn’t explicitly return anything, it will return `None` (like `print`).

Run the following cell and see if you can decipher what is happening.

In [3]:
def add_and_print(a, b):
    total = a + b
    print(total)

total = add_and_print(3, 4)
print("the sum of 3 and 4 is", total)

7
the sum of 3 and 4 is None

### Return statements exit a function

Once we reach a statement with a `return` keyword, our function is done running. Nothing after this **return statement** is run.

Below, `odd` checks if a number is even or odd by checking if the remainder modulo 2 is equal to (`==`) 1. If it is not, then it is zero, meaning that the number is divisible by two (and therefore even).

In [5]:
def odd(n):
    return n % 2 == 1
    print("this will never be printed!")

In [6]:
odd(15)

True

In [7]:
odd(2)

False

## Scope

In [11]:
def odd(n):
    print("value of n", n)
    return n % 2 == 1

In [13]:
odd(15)
print("n outside function", n)

value of n 15

NameError: name 'n' is not defined

From within a function, can find and read values of names defined **outside** of function scope

In [27]:
US_CODE = "+1"

In [32]:
def make_phone_number(local_phone):
    return US_CODE + local_phone

In [33]:
make_phone_number("(510)642-3143")

'+1(510)642-3143'

In [ ]:
make_phone_number("(510)642-5391")

### Task: What is the value of `total` after running this code?

In [8]:
total = 3
def square_and_cube(a, b):
    return a ** 2 + total ** b
    
total = square_and_cube(2, 3)

### **Task:** Create a function called `age()` that takes the `year` of birth of a person and produces their age in years.

In [5]:
def age(year):
    ...

### **Task:** Create a function called `name_and_age()` that:
- takes a person's `name` and `year` of birth (two arguments). 
- produces a sentence that states how old they are (such as, "Jeremy is 26 years old").

In [6]:
def name_and_age(name,year):
    ... 
    return ...

In [ ]:
name_and_age("Jeremy", 1999)

**STOP**

### Use functions on table columns with `apply`

##### **Task:** use the `name_and_age()` function on a table with `apply`!

In [ ]:
fam = Table().with_columns(
    'First Name', make_array('Jeremy', 'Olivia', 'Data 8'),
    'Birth Year', make_array(1999, 2005, 2015)
)
fam

In [ ]:
# your code here. see answers below

In [ ]:
fam.apply(age, 'Birth Year')

In [ ]:
fam.apply(name_and_age, 'First Name', 'Birth Year')

In [ ]:
fam.with_columns("Statement",
                 fam.apply(name_and_age, 'First Name', 'Birth Year'))

# Functions with Strings

In [ ]:
s = 'JuNiOR12'

# space to try out string methods

In [ ]:
'berkeley' in 'uc berkeley'

### **Task**: Make exciting greetings by adding the **Greeting** column as below.

| Holiday | Name | Greeting |
| --- | --- | --- |
| Hanukkah | Josh |  HAPPY HANUKKAH JOSH |
| New Year | Tracy | HAPPY NEW YEAR TRACY |
| Birthday | Jaspreet | HAPPY BIRTHDAY JASPREET |

    
See the solution below!

In [36]:
holidays = Table().with_columns(
    'Holiday', make_array('Hanukkah', 'New Year', 'Birthday'),
    'Name', make_array('Josh', 'Tracy', 'Jaspreet')
)
holidays

Holiday  | Name
Hanukkah | Josh
New Year | Tracy
Birthday | Jaspreet

In [45]:
# fill in this code

def make_greeting(holiday, name):
    return ...
    
holidays.with_columns(
    "Greeting",
    holidays.apply(make_greeting, "Holiday", "Name")
)

Holiday  | Name     | Greeting
Hanukkah | Josh     | Ellipsis
New Year | Tracy    | Ellipsis
Birthday | Jaspreet | Ellipsis

<details>
  <summary>Click for Solution</summary>

Various options. One reasonable approach:

```
def make_greeting(holiday, name):
    return "HAPPY " + holiday.upper() + " " + name.upper()
```

<br/>
One advanced approach, using `join`:
    
```  
def make_greeting(holiday, name):
    return ' '.join(["happy", holiday, name]).upper()
```
    

</details>

### **Challenge**: Convert phone numbers.

For example, `510-642-3141` should be formatted as `(510) 642-3141`.

_Hint_: Try using `split`. The `split` function returns a list of strings split by the delimiter; after conversion, lists can be indexed just like an array.

See the solution below!

In [46]:
res_halls = Table().with_columns(
    'Residence Hall', 
        make_array('Unit 1', 'Unit 2', 'Unit 3', 'Foothill',
                   'Clark Kerr', 'Blackwell', 'Martinez Commons'),
    'Phone',
        make_array('510-642-3141', '510-642-3143', '510-642-5391', '510-642-9703',
                   '510-642-6290', '510-423-3740', '510-642-8517')
)
res_halls

Residence Hall   | Phone
Unit 1           | 510-642-3141
Unit 2           | 510-642-3143
Unit 3           | 510-642-5391
Foothill         | 510-642-9703
Clark Kerr       | 510-642-6290
Blackwell        | 510-423-3740
Martinez Commons | 510-642-8517

In [51]:
def format_phone_number(phone):
    parts = ...
    return ...

# to check a single phone number
format_phone_number("510-642-3141")

'(510) 642-3141'

In [52]:
# then, check all numbers
res_halls.with_columns(
    "Formatted",
    res_halls.apply(format_phone_number, "Phone")
)

Residence Hall   | Phone        | Formatted
Unit 1           | 510-642-3141 | (510) 642-3141
Unit 2           | 510-642-3143 | (510) 642-3143
Unit 3           | 510-642-5391 | (510) 642-5391
Foothill         | 510-642-9703 | (510) 642-9703
Clark Kerr       | 510-642-6290 | (510) 642-6290
Blackwell        | 510-423-3740 | (510) 423-3740
Martinez Commons | 510-642-8517 | (510) 642-8517

<details>
  <summary>Click for Solution</summary>

Various options. One reasonable approach:

```
def format_phone_number(phone):
    parts = np.array(phone.split('-'))
    return "(" + parts.item(0) + ") " + parts.item(1) + "-" + parts.item(2)
```
    

</details>